import sys

from paranames.util import read, write
import click


@click.command()
@click.option(
    "-a",
    "--alias-column",
    default="alias",
    help="Name of column containing the transliterated names.",
)
@click.option(
    "-e",
    "--english-column",
    default="eng",
    help="Name of column containing the English names.",
)
@click.option(
    "-r",
    "--romanized-column",
    default="romanized",
    help="Name of column containing romanizations generated by uroman.",
)
@click.option(
    "-ed",
    "--edit-distance-column",
    default="edit_distance",
    help="Name of column containing edit distances.",
)
@click.option("-f", "--io-format", default="tsv")
@click.option("-n", "--num-workers", default=1, type=int)
def main(
    alias_column,
    english_column,
    romanized_column,
    edit_distance_column,
    io_format,
    num_workers,
):
    with sys.stdin as standard_input, sys.stdout as standard_output:
        data = read(input_file=standard_input, io_format=io_format).drop(
            columns=[romanized_column, edit_distance_column], errors="ignore"
        )
        write(data, standard_output, io_format)


if __name__ == "__main__":
    main()
