#!/usr/bin/env python

from paranames.util.script import UnicodeAnalyzer
import orjson
import click


@click.command()
@click.argument("input_file", type=click.File("r"), default="-")
@click.argument("output_file", type=click.File("w"), default="-")
@click.option("--strip", is_flag=True)
@click.option("--no-normalize", is_flag=True)
def main(input_file, output_file, strip, no_normalize):

    ua = UnicodeAnalyzer(strip=strip, normalize_histogram=not no_normalize)

    with input_file, output_file:
        for line in input_file:
            hist = ua.icu_script_histogram(line)
            try:
                json_obj = orjson.dumps(hist).decode("utf-8")
            except:
                print(hist, file=open("/tmp/error_producing_hist", "w"))
                raise ValueError
            output_file.write(f"{json_obj}\n")


if __name__ == "__main__":
    main()
