#!/usr/bin/env python

from paranames.util.script import UnicodeAnalyzer
import click
import icu


@click.command()
@click.argument("input_file", type=click.File("r"), default="-")
@click.argument("output_file", type=click.File("w"), default="-")
@click.option("--strip", is_flag=True)
def main(input_file, output_file, strip):
    ua = UnicodeAnalyzer(strip=strip)
    with input_file, output_file:
        for line in input_file:
            script = ua.most_common_icu_script(line)
            output_file.write(f"{script}\n")


if __name__ == "__main__":
    main()
